version: "3.6"
services:
  db:
    image: postgres:12.2
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
volumes:
  data:
    external: false